### ISSUE TITLE
Timeout/UnhandledPromiseRejectionWarning on StackOverflow Login Form

### ISSUE THREAD

**Issue by EelcoLos** [garsaud/stackoverflow-fanatic-badge#9]
#### Issue description

I'm trying to get this bot running properly and got this issue since April 5th (according to the logs)

#### Steps to reproduce the issue

1.  Get the docker image running according to the [setup](https://github.com/garsaud/stackoverflow-fanatic-badge#with-a-config-file) path and have a valid login,password & mailgun config.
2. use the docker run command 

#### What's the expected result?
- That the bot will log in on stackoverflow and count for the consecutive days, all the way to the fanatic badge.

#### What's the actual result?
This is one of the sets of logs items. The rejection id at the end is different every time:
```
Loading https://stackoverflow.com/users/login
 -> success!
Filling login form with credentials
(node:9) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /node_modules/puppeteer/lib/LifecycleWatcher.js:143:21
    at async FrameManager.waitForFrameNavigation (/node_modules/puppeteer/lib/FrameManager.js:120:19)
    at async Frame.waitForNavigation (/node_modules/puppeteer/lib/FrameManager.js:393:12)
    at async Page.waitForNavigation (/node_modules/puppeteer/lib/Page.js:676:12)
    at async Promise.all (index 1)
    at async crawl (/app.js:47:5)
  -- ASYNC --
    at Frame.<anonymous> (/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.waitForNavigation (/node_modules/puppeteer/lib/Page.js:676:49)
    at Page.<anonymous> (/node_modules/puppeteer/lib/helper.js:109:23)
    at crawl (/app.js:49:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by garsaud** [comment]
Sorry for the late answer. This issue is fixed in [v1.1.0](https://github.com/garsaud/stackoverflow-fanatic-badge/releases/tag/v1.1.0).

It should be perfetly stable now. I have been running the bot for more than 200 days without interruption:
![Screenshot of my stackoverflow profile, showing 228 consecutive visits](https://user-images.githubusercontent.com/3667366/204245157-ffe10b12-b056-4a01-89e2-e64f73b68cff.png)
